import type { Transaction } from './types'

export const mockTransactions: Transaction[] = [
  {
    id: '1',
    description: 'Monthly Salary',
    amount: 5000,
    type: 'income',
    category: 'Salary',
    date: '2026-04-01',
  },
  {
    id: '2',
    description: 'Freelance Project',
    amount: 1200,
    type: 'income',
    category: 'Freelance',
    date: '2026-04-03',
  },
  {
    id: '3',
    description: 'Grocery Shopping',
    amount: 150,
    type: 'expense',
    category: 'Food',
    date: '2026-04-02',
  },
  {
    id: '4',
    description: 'Electric Bill',
    amount: 85,
    type: 'expense',
    category: 'Bills',
    date: '2026-04-05',
  },
  {
    id: '5',
    description: 'Gas Station',
    amount: 60,
    type: 'expense',
    category: 'Transportation',
    date: '2026-04-04',
  },
  {
    id: '6',
    description: 'Restaurant Dinner',
    amount: 75,
    type: 'expense',
    category: 'Food',
    date: '2026-04-05',
  },
  {
    id: '7',
    description: 'Stock Dividends',
    amount: 320,
    type: 'income',
    category: 'Investments',
    date: '2026-04-06',
  },
  {
    id: '8',
    description: 'Netflix Subscription',
    amount: 15,
    type: 'expense',
    category: 'Entertainment',
    date: '2026-04-01',
  },
  {
    id: '9',
    description: 'New Shoes',
    amount: 120,
    type: 'expense',
    category: 'Shopping',
    date: '2026-03-28',
  },
  {
    id: '10',
    description: 'Doctor Visit',
    amount: 100,
    type: 'expense',
    category: 'Healthcare',
    date: '2026-03-25',
  },
  {
    id: '11',
    description: 'Internet Bill',
    amount: 60,
    type: 'expense',
    category: 'Bills',
    date: '2026-03-20',
  },
  {
    id: '12',
    description: 'Coffee Shop',
    amount: 25,
    type: 'expense',
    category: 'Food',
    date: '2026-03-22',
  },
  {
    id: '13',
    description: 'Uber Rides',
    amount: 45,
    type: 'expense',
    category: 'Transportation',
    date: '2026-03-18',
  },
  {
    id: '14',
    description: 'Gym Membership',
    amount: 50,
    type: 'expense',
    category: 'Healthcare',
    date: '2026-03-15',
  },
  {
    id: '15',
    description: 'Side Gig Payment',
    amount: 500,
    type: 'income',
    category: 'Freelance',
    date: '2026-03-10',
  },
]

export const incomeCategories = ['Salary', 'Freelance', 'Investments', 'Other'] as const
export const expenseCategories = ['Food', 'Transportation', 'Entertainment', 'Shopping', 'Bills', 'Healthcare', 'Other'] as const
export const allCategories = [...incomeCategories, ...expenseCategories] as const
